name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.EMAIL }}
      run: |
          echo "user.email=$env:SUPER_SECRET" >> src/main/resources/application.properties
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.PASSWORD }}
      run: |
          echo "user.password=$env:SUPER_SECRET" >> src/main/resources/application.properties
    - name: Maven clean install 
      run: mvn clean install >> mvn.txt
    - name: Build the Docker image
      run: docker build -t portfolio:$(date +%s) -f Dockerfile .
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: bitwisor07
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        build: false
        push: true
        tags: user/app:latest
