name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.EMAIL }}
      run: |
          echo "user.email=$SUPER_SECRET" >> src/main/resources/application.properties
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.PASSWORD }}
      run: |
          echo "user.password=$SUPER_SECRET" >> src/main/resources/application.properties
    - name: Maven clean install 
      run: mvn clean install >> mvn.txt
    - name: Build the Docker image
      run: docker build -t portfolio:$(date +%s) -f Dockerfile .
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: bitwisor07
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
          context: .
          push: true
          tags: bitwisor07/portfolio:latest
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.PEM }}
      run: |
          echo "$SUPER_SECRET" | base64 --decode > kp.pem
    - name: Set permissions for SSH key
      run: chmod 600 kp.pem
    - name: SSH into EC2 and run multiple commands
    - run: |
        ssh -o StrictHostKeyChecking=no -i kp.pem ec2-user@13.51.178.118 << 'EOF'
          sudo docker stop portfoliocontainer
          sudo docker rm portfoliocontainer
          sudo docker login --username bitwisor07 --password ${{ secrets.PASSWORD }}
          sudo docker pull bitwisor07/portfolio:latest
          sudo docker run --name=portfoliocontainer -d -p 80:8080 bitwisor07/portfolio:latest
        EOF
